# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_newMission.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDialog, QApplication, QPushButton, QVBoxLayout
from PyQt5.QtCore import QThread, pyqtSignal, QDateTime, QObject

from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.backends.backend_qt5agg import NavigationToolbar2QT as NavigationToolbar
import matplotlib.pyplot as plt
import random

from application.windowApp.main.Drone import Drone
from application.windowApp.main.BackendThread import BackendThread


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1792, 1008)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_8.addWidget(self.label)

        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout_8.addWidget(self.graphicsView)


        self.horizontalLayout.addLayout(self.verticalLayout_8)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_10.addWidget(self.label_5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)

        #uav detail ui
        self.lblAirspeed = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.lblAirspeed.setFont(font)
        self.lblAirspeed.setText("")
        self.lblAirspeed.setLineWidth(1)
        self.lblAirspeed.setTextFormat(QtCore.Qt.AutoText)
        self.lblAirspeed.setAlignment(QtCore.Qt.AlignCenter)
        self.lblAirspeed.setIndent(-1)
        self.lblAirspeed.setObjectName("lblAirspeed")
        self.verticalLayout_3.addWidget(self.lblAirspeed)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.lblGroundspeed = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.lblGroundspeed.setFont(font)
        self.lblGroundspeed.setText("")
        self.lblGroundspeed.setLineWidth(1)
        self.lblGroundspeed.setTextFormat(QtCore.Qt.AutoText)
        self.lblGroundspeed.setAlignment(QtCore.Qt.AlignCenter)
        self.lblGroundspeed.setIndent(-1)
        self.lblGroundspeed.setObjectName("lblGroundspeed")
        self.verticalLayout_3.addWidget(self.lblGroundspeed)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.lblAttitude = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.lblAttitude.setFont(font)
        self.lblAttitude.setText("")
        self.lblAttitude.setLineWidth(1)
        self.lblAttitude.setTextFormat(QtCore.Qt.AutoText)
        self.lblAttitude.setAlignment(QtCore.Qt.AlignCenter)
        self.lblAttitude.setIndent(-1)
        self.lblAttitude.setObjectName("lblAttitude")
        self.verticalLayout_2.addWidget(self.lblAttitude)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.lblHeading = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.lblHeading.setFont(font)
        self.lblHeading.setText("")
        self.lblHeading.setLineWidth(1)
        self.lblHeading.setTextFormat(QtCore.Qt.AutoText)
        self.lblHeading.setAlignment(QtCore.Qt.AlignCenter)
        self.lblHeading.setIndent(-1)
        self.lblHeading.setObjectName("lblHeading")
        self.verticalLayout_2.addWidget(self.lblHeading)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.lblAltitude = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.lblAltitude.setFont(font)
        self.lblAltitude.setText("")
        self.lblAltitude.setLineWidth(1)
        self.lblAltitude.setTextFormat(QtCore.Qt.AutoText)
        self.lblAltitude.setAlignment(QtCore.Qt.AlignCenter)
        self.lblAltitude.setIndent(-1)
        self.lblAltitude.setObjectName("lblAltitude")
        self.verticalLayout.addWidget(self.lblAltitude)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.lblVerticalSpeed = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.lblVerticalSpeed.setFont(font)
        self.lblVerticalSpeed.setLineWidth(1)
        self.lblVerticalSpeed.setText("")
        self.lblVerticalSpeed.setTextFormat(QtCore.Qt.AutoText)
        self.lblVerticalSpeed.setAlignment(QtCore.Qt.AlignCenter)
        self.lblVerticalSpeed.setIndent(-1)
        self.lblVerticalSpeed.setObjectName("lblVerticalSpeed")
        self.verticalLayout.addWidget(self.lblVerticalSpeed)
        #end uav detail ui

        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_10.addLayout(self.horizontalLayout_3)
        self.horizontalLayout.addLayout(self.verticalLayout_10)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_9.addWidget(self.label_9)
        self.graphicsView_3 = QtWidgets.QGraphicsView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.graphicsView_3.sizePolicy().hasHeightForWidth())
        self.graphicsView_3.setSizePolicy(sizePolicy)
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.verticalLayout_9.addWidget(self.graphicsView_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_9)

        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_7.addWidget(self.label_2)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_7.addWidget(self.pushButton)

        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 849, 1024))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")

        # store graphs

        self.verticalLayout_graphs = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_graphs.setObjectName("verticalLayout_graphs")

        """
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.graphicsView_2.sizePolicy().hasHeightForWidth())
        self.graphicsView_2.setSizePolicy(sizePolicy)
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.verticalLayout_7.addWidget(self.graphicsView_2)
        """
        # 1
        # draw graph
        self.figure = plt.figure(figsize=(1, 2.5))
        self.canvas = FigureCanvas(self.figure)
        self.canvas.setMinimumSize(self.canvas.size())
        # fig = plt.gcf()
        # fig.set_size_inches(5, 5)
        # self.toolbar = NavigationToolbar(self.canvas, self)
        plt.suptitle("Temperature")

        # test temperature
        data = [random.random() for i in range(10)]
        self.figure.clear()
        plt.suptitle("Temperature (C)")
        y = (25.2, 25.3, 25.4, 25.7, 25.6, 25.3, 25.4, 25.6, 25.6, 25.7)
        x = (5, 10, 15, 20, 25, 30, 35, 40, 45, 50)
        ax = self.figure.add_subplot(111)
        ax.plot(x, y)
        self.canvas.draw()

        # self.button = QPushButton('Plot')
        # self.button.clicked.connect(self.plot)
        # layout = QVBoxLayout()
        # self.verticalLayout_7.addWidget(self.toolbar)
        # self.verticalLayout_7.addWidget(self.canvas)
        self.verticalLayout_graphs.addWidget(self.canvas)

        # 2
        # draw graph
        self.figure = plt.figure(figsize=(1, 2.5))
        self.canvas = FigureCanvas(self.figure)
        self.canvas.setMinimumSize(self.canvas.size())
        # fig = plt.gcf()
        # fig.set_size_inches(5, 5)
        # self.toolbar = NavigationToolbar(self.canvas, self)
        plt.suptitle("Temperature")

        # test temperature
        data = [random.random() for i in range(10)]
        self.figure.clear()
        plt.suptitle("Temperature (C)")
        y = (25.2, 25.3, 25.4, 25.7, 25.6, 25.3, 25.4, 25.6, 25.6, 25.7)
        x = (5, 10, 15, 20, 25, 30, 35, 40, 45, 50)
        ax = self.figure.add_subplot(111)
        ax.plot(x, y)
        self.canvas.draw()
        self.verticalLayout_graphs.addWidget(self.canvas)
        # self.verticalLayout_7.addWidget(self.button)

        # 3
        # draw graph
        self.figure = plt.figure(figsize=(1, 2.5))
        self.canvas = FigureCanvas(self.figure)
        self.canvas.setMinimumSize(self.canvas.size())
        # fig = plt.gcf()
        # fig.set_size_inches(5, 5)
        # self.toolbar = NavigationToolbar(self.canvas, self)
        plt.suptitle("Temperature")

        # test temperature
        data = [random.random() for i in range(10)]
        self.figure.clear()
        plt.suptitle("Temperature (C)")
        y = (25.2, 25.3, 25.4, 25.7, 25.6, 25.3, 25.4, 25.6, 25.6, 25.7)
        x = (5, 10, 15, 20, 25, 30, 35, 40, 45, 50)
        ax = self.figure.add_subplot(111)
        ax.plot(x, y)
        self.canvas.draw()
        self.verticalLayout_graphs.addWidget(self.canvas)
        # self.verticalLayout_7.addWidget(self.button)
        # 4
        # draw graph
        self.figure = plt.figure(figsize=(1, 2.5))
        self.canvas = FigureCanvas(self.figure)
        self.canvas.setMinimumSize(self.canvas.size())
        # fig = plt.gcf()
        # fig.set_size_inches(5, 5)
        # self.toolbar = NavigationToolbar(self.canvas, self)
        plt.suptitle("Temperature")

        # test temperature
        data = [random.random() for i in range(10)]
        self.figure.clear()
        plt.suptitle("Temperature (C)")
        y = (25.2, 25.3, 25.4, 25.7, 25.6, 25.3, 25.4, 25.6, 25.6, 25.7)
        x = (5, 10, 15, 20, 25, 30, 35, 40, 45, 50)
        ax = self.figure.add_subplot(111)
        ax.plot(x, y)
        self.canvas.draw()
        self.verticalLayout_graphs.addWidget(self.canvas)
        # self.verticalLayout_7.addWidget(self.button)
        # 5
        # draw graph
        self.figure = plt.figure(figsize=(1, 2.5))
        self.canvas = FigureCanvas(self.figure)
        self.canvas.setMinimumSize(self.canvas.size())
        # fig = plt.gcf()
        # fig.set_size_inches(5, 5)
        # self.toolbar = NavigationToolbar(self.canvas, self)
        plt.suptitle("Temperature")

        # test temperature
        data = [random.random() for i in range(10)]
        self.figure.clear()
        plt.suptitle("Temperature (C)")
        y = (25.2, 25.3, 25.4, 25.7, 25.6, 25.3, 25.4, 25.6, 25.6, 25.7)
        x = (5, 10, 15, 20, 25, 30, 35, 40, 45, 50)
        ax = self.figure.add_subplot(111)
        ax.plot(x, y)
        self.canvas.draw()
        self.verticalLayout_graphs.addWidget(self.canvas)
        # self.verticalLayout_7.addWidget(self.button)

        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_7.addWidget(self.scrollArea)

        self.horizontalLayout_2.addLayout(self.verticalLayout_7)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)

        # Menu
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1792, 22))
        self.menubar.setObjectName("menubar")
        self.menuMission = QtWidgets.QMenu(self.menubar)
        self.menuMission.setObjectName("menuFile")
        self.menuConnection = QtWidgets.QMenu(self.menubar)
        self.menuConnection.setObjectName("menuConnection")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew_Mission = QtWidgets.QAction(MainWindow)
        self.actionNew_Mission.setObjectName("actionNew_Mission")
        self.actionView_Mission = QtWidgets.QAction(MainWindow)
        self.actionView_Mission.setObjectName("actionView_Mission")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        # quit
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionClose.triggered.connect(QApplication.quit)
        # connect
        self.actionConnect = QtWidgets.QAction(MainWindow)
        self.actionConnect.setObjectName("actionConnect")

        self.actionConnect.triggered.connect(self.connect)

        self.actionDisconnect = QtWidgets.QAction(MainWindow)
        self.actionDisconnect.setObjectName("actionDisconnect")
        self.actionDisconnect.triggered.connect(self.disconnect)
        self.menuMission.addAction(self.actionNew_Mission)
        self.menuMission.addAction(self.actionSave)
        self.menuMission.addAction(self.actionClose)
        self.menuConnection.addAction(self.actionConnect)
        self.menuConnection.addAction(self.actionDisconnect)
        self.menubar.addAction(self.menuMission.menuAction())
        self.menubar.addAction(self.menuConnection.menuAction())
        # menu button setting
        self.actionConnect.setDisabled(False)
        self.actionDisconnect.setDisabled(True)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.menubar.setNativeMenuBar(False)  # False for current window, True for parent window

        # update detail
        self.backend = BackendThread()
        self.backend.update_detail.connect(self.updateDetail)
        self.thread = QThread()
        self.backend.moveToThread(self.thread)
        # start thread
        self.thread.started.connect(self.backend.run)
        self.thread.start()

    def updateDetail(self, detail):
        self.lblAirspeed.setText(str(detail['airspeed']))
        self.lblAttitude.setText(str(detail['attitude_pitch'])+"\n"+str(detail['attitude_yaw'])+"\n"+str(detail['attitude_roll']))
        self.lblAltitude.setText(str(detail['altitude']))
        self.lblGroundspeed.setText(str(detail['groundspeed']))
        self.lblHeading.setText( str(detail["heading"]))
        self.lblVerticalSpeed.setText(str(detail['verticalSpeed']))

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Automated Data Collecting System"))
        self.label.setText(_translate("MainWindow", "Streaming"))
        self.label_5.setText(_translate("MainWindow", "UAV Details"))
        self.label_7.setText(_translate("MainWindow", "Airspeed"))
        self.label_6.setText(_translate("MainWindow", "Groundspeed"))
        self.label_4.setText(_translate("MainWindow", "Attitude"))
        self.label_3.setText(_translate("MainWindow", "Heading"))
        self.label_8.setText(_translate("MainWindow", "Altitude"))
        self.label_10.setText(_translate("MainWindow", "Vertical Speed"))
        self.label_9.setText(_translate("MainWindow", "Map"))
        self.label_2.setText(_translate("MainWindow", "Data Collection"))
        self.pushButton.setText(_translate("MainWindow", "Start"))
        self.menuMission.setTitle(_translate("MainWindow", "Mission"))
        self.menuConnection.setTitle(_translate("MainWindow", "Connection"))
        self.actionNew_Mission.setText(_translate("MainWindow", "New Mission"))
        self.actionView_Mission.setText(_translate("MainWindow", "View Mission"))
        self.actionSave.setText(_translate("MainWindow", "Output Result"))
        self.actionClose.setText(_translate("MainWindow", "Quit"))
        self.actionConnect.setText(_translate("MainWindow", "Connect"))
        self.actionDisconnect.setText(_translate("MainWindow", "Disconnect"))
    """
        def plot(self):
        data = [random.random() for i in range(10)]
        self.figure.clear()
        plt.suptitle("Temperature (C)")
        ax = self.figure.add_subplot(111)
        ax.plot(data, '*-')
        self.canvas.draw()
    """

    def connect(self):
        #self.drone = Drone('tcp:127.0.0.1:5760')
        self.drone = Drone('udp:0.0.0.0:14550')
        self.vehicle = self.drone.getDrone()
        self.actionConnect.setDisabled(True)
        self.actionDisconnect.setDisabled(False)
        # print(*self.detail.items(),sep='\n')
        """
        print(self.detail["airSpeed"])
        print(self.detail["attltude"])
        print(self.detail["heading"])
        self.label_7.setText("Airspeed" + ": " + str(self.detail["airSpeed"]))
        self.label_4.setText("Attitude" + ": \n" + str(self.detail["attltude"]).replace(",", "\n"))
        self.label_3.setText("Heading" + ": " + str(self.detail["heading"]))
        """
        self.backend.setVehicle(self.vehicle)

    def disconnect(self):
        self.drone.disconnectDrone()
        self.actionConnect.setDisabled(False)
        self.actionDisconnect.setDisabled(True)
        self.backend.exist=False
